a = Analysis(['tweet.py'],
             pathex=['/Users/dylanwhite/Desktop/'],
             binaries=[],
             datas=[],
             hiddenimports=['youtube_transcript_api'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=None,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=None)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='InstaSumUp',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False)
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='InstaSumUp')
app = BUNDLE(coll,
             name='InstaSumUp.app',
             icon=None,
             bundle_identifier=None)
